# Generated by Django 2.2.4 on 2019-09-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('genres', models.CharField(max_length=15)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('vid', models.FileField(upload_to='')),
            ],
        ),
    ]
